-- 기존 객체가 있다면 삭제 (에러가 나도 무시하고 진행하세요)
DROP TABLE ATTENDANCE CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_ATTENDANCE_ID;

-- 출석 테이블 생성
CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ATTENDANCE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CONSECUTIVE_DAYS NUMBER DEFAULT 1 NOT NULL,
    POINTS_EARNED NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_ATTENDANCE_USER FOREIGN KEY (USER_ID) REFERENCES MEMBER(MEMBER_ID)
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_ATTENDANCE_ID;

-- (참고) 포인트 지갑 테이블 (이미 존재한다고 가정하지만 없다면 생성 필요)
-- CREATE TABLE POINT_WALLET (
--     WALLET_ID NUMBER PRIMARY KEY,
--     MEMBER_ID NUMBER UNIQUE,
--     NOW_POINT NUMBER DEFAULT 0,
--     UPDATED_AT DATE DEFAULT SYSDATE
-- );
