-- ==========================================
-- [에코트리 프로젝트 SQL]
-- 담당: AI (Antigravity)
-- 목적: 누적 포인트를 활용한 나무 성장 시스템
-- ==========================================

-- 1. 에코트리 테이블 (기존 테이블 삭제 후 재생성)
DROP TABLE ECO_TREE CASCADE CONSTRAINTS;

CREATE TABLE ECO_TREE (
    MEMBER_ID           NUMBER NOT NULL,
    TREE_LEVEL          NUMBER DEFAULT 1 NOT NULL, -- 1: 씨앗/새싹, 2: 어린나무, 3: 큰나무, 4: 열매나무
    SYNCED_EXP          NUMBER DEFAULT 0 NOT NULL, -- 나무 처리에 반영된 누적 포인트(경험치)
    LAST_GROWTH_DATE    DATE DEFAULT SYSDATE,      -- 마지막으로 성장 버튼을 누른 날짜
    CONSTRAINT PK_ECO_TREE PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_ECO_TREE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID) ON DELETE CASCADE
);

COMMENT ON COLUMN ECO_TREE.MEMBER_ID IS '회원 고유 ID (PK)';
COMMENT ON COLUMN ECO_TREE.TREE_LEVEL IS '나무 성장 단계 (1~4)';
COMMENT ON COLUMN ECO_TREE.SYNCED_EXP IS '나무 성장에 반영된 누적 포인트';

-- 2. 새 회원 가입 시 에코트리 자동 생성 트리거
CREATE OR REPLACE TRIGGER TRG_MEMBER_ECO_TREE_INIT
AFTER INSERT ON MEMBER
FOR EACH ROW
BEGIN
    INSERT INTO ECO_TREE (MEMBER_ID, TREE_LEVEL, SYNCED_EXP)
    VALUES (:NEW.MEMBER_ID, 1, 0);
END;
/

-- 3. 기존 데이터가 있을 경우를 대비한 초기화 (필요시 실행)
-- INSERT INTO ECO_TREE (MEMBER_ID, TREE_LEVEL, SYNCED_EXP)
-- SELECT MEMBER_ID, 1, 0 FROM MEMBER M
-- WHERE NOT EXISTS (SELECT 1 FROM ECO_TREE E WHERE E.MEMBER_ID = M.MEMBER_ID);
