-- QUEST 데이터 삽입 스크립트
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '양치할 때 컵 사용하기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '샤워 시간 1분 줄이기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '안 쓰는 방 불 끄기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '에코백 들고 시장 가기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '대중교통으로 등교/출근하기', 150, '출퇴근');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '이동 시 계단 3층 걷기', 10, '출퇴근');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '이면지를 연습장으로 활용하기', 10, '등하원');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '개인 텀블러 소지하기', 10, '등하원');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '잔반 한 톨 안 남기기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '라벨 떼고 페트병 배출', 100, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '미사용 가전 코드 뽑기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '배달 수저 안 받기 체크', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '손수건 사용해서 휴지 아끼기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '전자 영수증으로 받기', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '가까운 동네 걷기 여행', 10, '일상생활');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '텀블러 사용 인증하기', 100, '에너지 절약');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '대중교통 이용하기', 150, '탄소 줄이기');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '장바구니 사용하기', 100, '제로 웨이스트');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '안 쓰는 플러그 뽑기', 50, '에너지 절약');
INSERT INTO QUEST (QUEST_NO, QUEST_TITLE, POINT, CATEGORY) VALUES (SEQ_QUEST_NO.NEXTVAL, '분리수거 철저히 하기', 100, '재활용');

COMMIT;
