-- QUIZ 데이터 삽입 스크립트 (총 150문항 중 주요 샘플 30문항 수록)
-- [Easy - 10문항]
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '플라스틱 분리배출 표시 마크 내부의 숫자가 의미하는 것은?', '생산 연도', '재활용 등급', '플라스틱 재질 번호', '공장 고유 번호', 3, '플라스틱 재질에 따라 숫자가 부여되어 재활용 시 분류 기준으로 사용됩니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '올바른 분리배출 방법이 아닌 것은?', '비우기', '헹구기', '라벨 떼기', '음식물이 묻은 채로 버리기', 4, '음식물이 묻은 용기는 재활용이 불가능하며 종량제 봉투에 담아 버려야 합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '여름철 실내 적정 온도로 가장 적절한 것은?', '18도 이하', '20-22도', '24-26도', '28도 이상', 3, '여름철 에너지 절약을 위한 실내 적정 온도는 24~26도입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '종이팩과 종이류는 어떻게 배출해야 하나요?', '함께 섞어서 배출', '종량이 봉투에 배출', '종이팩 전용함에 따로 배출', '태워서 배출', 3, '종이팩은 우유팩, 두유팩 등 고급 펄프로 만들어져 일반 종이와 구분해 배출해야 합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '에어컨을 효율적으로 사용하는 방법 중 틀린 것은?', '처음 켤 때 강풍으로 설정', '선풍기와 함께 사용', '문을 열고 냉방', '필터 주기적 청소', 3, '문을 열고 냉방하면 냉각 효율이 떨어져 에너지 낭비가 매우 큽니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '지구 온난화의 주범으로 불리는 가스는?', '산소', '이산화탄소', '질소', '헬륨', 2, '이산화탄소는 온실 효과를 일으켜 지구 온도를 높이는 주된 원인입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '쓰레기가 썩는 데 가장 오래 걸리는 것은?', '종이', '우유팩', '스티로폼', '나무젓가락', 3, '스티로폼은 자연 분해되는 데 500년 이상이 걸리는 것으로 알려져 있습니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '나무를 심으면 좋은 이유가 아닌 것은?', '공기 정화', '이산화탄소 흡수', '홍수 예방', '미세먼지 농도 증가', 4, '나무는 미세먼지를 흡수하고 차단하여 농도를 낮추는 역할을 합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '양치할 때 물을 절약하는 방법은?', '물을 계속 틀어두기', '양치 컵 사용하기', '손으로 물 받기', '물 안 쓰기', 2, '양치 컵을 사용하면 흘려보내는 물을 획기적으로 줄일 수 있습니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Easy', 10, '물티슈의 주성분은 무엇인가요?', '순수한 면', '종이', '플라스틱(폴리에스테르)', '대나무', 3, '대부분의 물티슈는 플라스틱 성분으로 만들어져 변기에 버리면 막힘과 환경오염의 원인이 됩니다.');

-- [Normal - 10문항]
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '제품의 전 과정에서 발생하는 온실가스 배출량을 표시하는 제도는?', '에너지 효율 등급', '탄소발자국', '저탄소 인증', '환경 성적 표지', 2, '탄소발자국은 제품의 생산부터 폐기까지의 온실가스 발생량을 의미합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '포인트 적립을 통해 친환경 소비를 독려하는 제도는?', '에코 마일리지', '그린카드', '탄소포인트제', '모두 정답', 4, '그린카드와 에코머니, 탄소포인트제 등은 모두 친환경 생활을 독려하는 제도입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '업사이클링(Upcycling)의 의미는?', '그대로 재사용', '재활용하여 품질이 낮은 가치로 만듦', '디자인이나 활용도를 더해 가치가 높은 제품으로 재탄생', '단순 수거', 3, '업사이클링은 단순 재활용을 넘어 가치를 높이는 창조적 재사용을 뜻합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '지속가능발전목표(SDGs)의 목표 개수는?', '10개', '17개', '21개', '30개', 2, 'UN은 인류의 발전을 위해 17가지의 핵심 목표를 설정하였습니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '미세먼지 농도가 높은 날의 행동 요령이 아닌 것은?', '외출 시 보건용 마스크 착용', '외출 후 손 씻기', '창문을 하루 종일 열어두기', '단백질과 수분 섭취', 3, '환기는 짧게 하고, 미세먼지가 너무 심한 시간대는 피해야 합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '생물 다양성 보전의 중요성이 아닌 것은?', '생태계 균형 유지', '미래 자원 확보', '특정 종의 독점적 번성', '자연 정화 능력 유지', 3, '특정 종이 독점하는 것이 아니라 모든 종이 함께 공존하는 것이 핵심입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '바이오매스(Biomass) 에너지의 원천은?', '화석 연료', '우라늄', '동물과 식물 등의 유기물', '햇빛', 3, '바이오에너지는 식물, 미생물, 농업 부산물 등에서 에너지를 얻는 방식입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '제로 웨이스트(Zero Waste) 운동의 5R 원칙 중 거절하기는?', 'Refuse', 'Reduce', 'Reuse', 'Recycle', 1, 'Refuse(거절하기)는 불필요한 일회용품이나 쓰레기를 받지 않는 것입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '태양광 발전의 장점이 아닌 것은?', '무한한 자원', '유지 관리비가 저렴', '날씨의 영향을 받지 않음', '탄소 배출 없음', 3, '태양광은 일사량과 날씨 등 기상 조건에 큰 영향을 받습니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Normal', 20, '로컬 푸드(Local Food) 구매의 친환경적 이점은?', '맛이 더 좋음', '장거리 운송 과정의 탄소 배출 감소', '포장지가 화려함', '해외 직구 가능', 2, '가까운 곳의 먹거리를 이용하면 푸드 마일리지가 줄어들어 탄소 발생이 줄어듭니다.');

-- [Hard - 10문항]
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '신기후체제의 기반이 된 2015년 협정은?', '리우 협정', '파리 협정', '교토의정서', '몬트리올 의정서', 2, '파리 협정은 당사국 모두가 온실가스 감축 목표를 수립하는 역사적 합의입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, 'RE100 캠페인에서 목표로 하는 재생에너지 비율은?', '30%', '50%', '80%', '100%', 4, '기업이 사용하는 전력 100%를 재생에너지로 바꾸는 글로벌 캠페인입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '람사르 협약은 무엇을 보호하기 위한 협약인가?', '남극 대륙', '멸종 위기 동물', '습지', '대기권', 3, '습지의 보전과 지속 가능한 이용을 위한 국제 협약입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '기후변화에 관한 정부 간 협의체를 부르는 약칭은?', 'UNEP', 'IPCC', 'WHO', 'UNESCO', 2, 'IPCC는 기후 변화의 위험성을 평가하고 보고서를 작성하는 국제기구입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '환경 보호를 위해 오염자가 복구 비용을 부담해야 한다는 원칙은?', '무과실 책임 원칙', '오염자 부담 원칙(PPP)', '사전 예방의 원칙', '상응 대가 원칙', 2, 'Polluter Pays Principle(PPP)은 오염을 만든 자가 그 비용을 낸다는 원칙입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '그린 워싱(Greenwashing)의 의미는?', '친환경 청소 서비스', '제품을 초록색으로 칠하기', '위장 환경 주의 (친환경인 척 속이는 마케팅)', '자연 분해되는 세제', 3, '실제로는 그렇지 않으면서 친환경적인 것처럼 홍보하는 행위를 비판하는 용어입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '탄소 국경세(CBAM)의 주요 특징은?', '관광객에게 부과하는 세금', '수입 품목의 탄소 배출량에 부과하는 무역 관세', '나무 심기 기부금', '탄소 사용 시 주는 보조금', 2, '탄소 규제가 약한 국가에서 수입되는 제품에 대해 탄소 비용을 부과하는 제도입니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, 'ESG 경영의 구성 요소가 아닌 것은?', 'Environment(환경)', 'Social(사회)', 'Governance(지배구조)', 'Economics(경제성)', 4, 'ESG는 기업의 비재무적 요소인 환경, 사회, 지배구조를 의미합니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '오존층 파괴의 주범인 프레온 가스의 공식 명칭은?', 'CFCs', 'GHGs', 'VOCs', 'PM2.5', 1, '염화불화탄소(CFCs)는 오존층을 파괴하여 사용이 점진적으로 금지되었습니다.');
INSERT INTO QUIZ (QUIZ_NO, DIFFICULTY, POINT, QUIZ_QUESTION, OPTION1, OPTION2, OPTION3, OPTION4, QUIZ_ANSWER, QUIZ_EXPLANATION) VALUES (SEQ_QUIZ_NO.NEXTVAL, 'Hard', 50, '지속 가능한 생태계를 위해 전 세계 해양의 30%를 보호구역으로 지정하자는 구상은?', 'COP26', '30 by 30', 'G20 선언', 'UN 2030', 2, '2030년까지 전 지구 육상과 해양의 최소 30%를 보호하자는 생물다양성 목표입니다.');

COMMIT;
