-- ─── Quest ───
CREATE TABLE IF NOT EXISTS QUEST (
    QUEST_NO    NUMBER PRIMARY KEY,
    QUEST_TITLE VARCHAR(200),
    POINT       NUMBER,
    CATEGORY    VARCHAR(50),
    CREATED_AT  TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS SEQ_QUEST_HISTORY_NO START WITH 1;

CREATE TABLE IF NOT EXISTS QUEST_HISTORY (
    HISTORY_ID  NUMBER PRIMARY KEY,
    MEMBER_ID   NUMBER,
    QUEST_NO    NUMBER,
    IMAGE_URL   VARCHAR(500),
    STATUS      CHAR(1) DEFAULT 'N',
    CREATED_AT  TIMESTAMP
);

-- ─── Attendance ───
CREATE TABLE IF NOT EXISTS ATTENDANCE (
    ATTENDANCE_ID    NUMBER PRIMARY KEY,
    USER_ID          NUMBER,
    ATTENDANCE_DATE  TIMESTAMP,
    CONSECUTIVE_DAYS NUMBER,
    POINTS_EARNED    NUMBER
);

CREATE SEQUENCE IF NOT EXISTS SEQ_ATTENDANCE_ID START WITH 1;

-- ─── Point Wallet (출석 포인트 업데이트용) ───
CREATE TABLE IF NOT EXISTS POINT_WALLET (
    MEMBER_ID     NUMBER PRIMARY KEY,
    NOW_POINT     NUMBER DEFAULT 2000,
    TOTAL_EARNED  NUMBER DEFAULT 0,
    TOTAL_SPENT   NUMBER DEFAULT 0,
    UPDATED_AT    TIMESTAMP
);
-- ─── Quiz ───
CREATE TABLE IF NOT EXISTS QUIZ (
    QUIZ_NO          NUMBER PRIMARY KEY,
    DIFFICULTY       VARCHAR(20),
    POINT            NUMBER,
    QUIZ_QUESTION    VARCHAR(1000),
    OPTION1          VARCHAR(500),
    OPTION2          VARCHAR(500),
    OPTION3          VARCHAR(500),
    OPTION4          VARCHAR(500),
    QUIZ_ANSWER      NUMBER,
    QUIZ_EXPLANATION VARCHAR(2000),
    CREATED_AT       TIMESTAMP
);

-- ─── Quiz History ───
CREATE TABLE IF NOT EXISTS QUIZ_HISTORY (
    HISTORY_ID NUMBER PRIMARY KEY,
    MEMBER_ID  NUMBER,
    DIFFICULTY VARCHAR(20),
    SCORE      NUMBER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS SEQ_QUIZ_HISTORY_NO START WITH 1;
